Update deployment.yaml

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -1,4 +1,4 @@
-# .github/workflows/deploy.yml
+# .github/workflows/deploy.yml 
 name: Deploy Docker Image
 
 on:
@@ -21,23 +21,23 @@ jobs:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Get Git commit hash and current date
-        id: vars
+      - name: Get the latest image tag
+        id: get_latest_image
         run: |
-          GIT_HASH=$(git rev-parse --short HEAD)
-          DATE_TAG=$(date +"%Y-%m-%d-%H%M")
-          echo "GIT_HASH=$GIT_HASH" >> $GITHUB_ENV
-          echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV
-          echo "TAG=${GIT_HASH}-${DATE_TAG}" >> $GITHUB_ENV
+          # Get the latest tag from Docker Hub (based on the most recent push)
+          LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/hello-world/tags/" | jq -r '.results[0].name')  # Get the most recent tag
+          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
+          echo "Latest Docker image tag: $LATEST_TAG"  # Just to verify it
 
-      - name: Pull Docker image
+      - name: Pull the latest Docker image
         id: pull_image
         run: |
-          docker pull ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ env.TAG }}
-#          if [ $? -ne 0 ]; then
-#            echo "Docker image pull failed!"
-#            exit 1
-#          fi
+          echo "Pulling the latest image with tag $LATEST_TAG"
+          docker pull ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ env.LATEST_TAG }}
+ #         if [ $? -ne 0 ]; then
+ #           echo "Docker image pull failed!"
+ #           exit 1
+ #         fi
 
       - name: Stop & Remove Existing Containers
         id: stop_remove_containers
@@ -47,9 +47,10 @@ jobs:
 
       - name: Run Docker Container
         run: |
-          docker run -d -p 80:3000 --name hello-world ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ env.TAG }}
-#          docker ps -a | grep hello-world
-#          if [ $? -ne 0 ]; then
-#            echo "Docker container failed to start!"
-#            exit 1
-#          fi
+          docker run -d -p 80:3000 --name hello-world ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ env.LATEST_TAG }}
+          docker ps -a | grep hello-world
+ #         if [ $? -ne 0 ]; then
+ #           echo "Docker container failed to start!"
+ #           exit 1
+ #         fi
+
