Update deployment.yaml

diff --git a/.github/workflows/deployment.yaml b/.github/workflows/deployment.yaml
--- a/.github/workflows/deployment.yaml
+++ b/.github/workflows/deployment.yaml
@@ -34,10 +34,10 @@ jobs:
         id: pull_image
         run: |
           docker pull ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ env.TAG }}
-          if [ $? -ne 0 ]; then
-            echo "Docker image pull failed!"
-            exit 1
-          fi
+#          if [ $? -ne 0 ]; then
+#            echo "Docker image pull failed!"
+#            exit 1
+#          fi
 
       - name: Stop & Remove Existing Containers
         id: stop_remove_containers
@@ -48,8 +48,8 @@ jobs:
       - name: Run Docker Container
         run: |
           docker run -d -p 80:3000 --name hello-world ${{ secrets.DOCKER_USERNAME }}/hello-world:${{ env.TAG }}
-          docker ps -a | grep hello-world
-          if [ $? -ne 0 ]; then
-            echo "Docker container failed to start!"
-            exit 1
-          fi
+#          docker ps -a | grep hello-world
+#          if [ $? -ne 0 ]; then
+#            echo "Docker container failed to start!"
+#            exit 1
+#          fi
